use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# WeeklySurveyWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :weekly_survey, WeeklySurveyWeb.Endpoint,
  load_from_system_env: true,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :weekly_survey, WeeklySurveyWeb.Endpoint,
  secret_key_base: System.get_env("SECRET_KEY_BASE") || throw "No SECRET_KEY_BASE ENV detected"

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :weekly_survey, WeeklySurvey.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "weekly_survey_prod",
  pool_size: 15

config :weekly_survey, WeeklySurvey.Users.EncryptedGuid,
  secret: {:system, "USERS_ENCRYPTION_SECRET"}
